-- MySQL Script generated by MySQL Workbench
-- Sat Aug 23 12:13:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jacquin_academia_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jacquin_academia_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jacquin_academia_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `jacquin_academia_db` ;

-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `correo_electronico` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `tipo_usuario` ENUM('Administrador', 'Profesor', 'Estudiante') NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_electronico` (`correo_electronico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`administrador` (
  `id_admin` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_admin`),
  INDEX `fk_admin_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_admin_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jacquin_academia_db`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`aula` (
  `id_aula` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_aula` VARCHAR(100) NOT NULL,
  `capacidad` INT(11) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`curso` (
  `id_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`horario` (
  `id_horario` INT(11) NOT NULL AUTO_INCREMENT,
  `dia_semana` VARCHAR(20) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`profesor` (
  `id_profesor` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_profesor`),
  INDEX `fk_profesor_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jacquin_academia_db`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`clase` (
  `id_clase` INT(11) NOT NULL AUTO_INCREMENT,
  `id_curso` INT(11) NOT NULL,
  `id_profesor` INT(11) NOT NULL,
  `id_aula` INT(11) NOT NULL,
  `id_horario` INT(11) NOT NULL,
  PRIMARY KEY (`id_clase`),
  INDEX `fk_clase_curso` (`id_curso` ASC) VISIBLE,
  INDEX `fk_clase_profesor` (`id_profesor` ASC) VISIBLE,
  INDEX `fk_clase_aula` (`id_aula` ASC) VISIBLE,
  INDEX `fk_clase_horario` (`id_horario` ASC) VISIBLE,
  CONSTRAINT `fk_clase_aula`
    FOREIGN KEY (`id_aula`)
    REFERENCES `jacquin_academia_db`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `jacquin_academia_db`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_horario`
    FOREIGN KEY (`id_horario`)
    REFERENCES `jacquin_academia_db`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clase_profesor`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `jacquin_academia_db`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`estudiante` (
  `id_estudiante` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `fecha_inscripcion` DATE NOT NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `fk_estudiante_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `jacquin_academia_db`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`asistencia` (
  `id_asistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `id_clase` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_asistencia`),
  INDEX `fk_asistencia_estudiante` (`id_estudiante` ASC) VISIBLE,
  INDEX `fk_asistencia_clase` (`id_clase` ASC) VISIBLE,
  CONSTRAINT `fk_asistencia_clase`
    FOREIGN KEY (`id_clase`)
    REFERENCES `jacquin_academia_db`.`clase` (`id_clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencia_estudiante`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `jacquin_academia_db`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jacquin_academia_db`.`inscripcioncurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jacquin_academia_db`.`inscripcioncurso` (
  `id_inscripcion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `id_curso` INT(11) NOT NULL,
  `fecha_inscripcion` DATE NOT NULL,
  PRIMARY KEY (`id_inscripcion`),
  INDEX `fk_inscripcion_estudiante` (`id_estudiante` ASC) VISIBLE,
  INDEX `fk_inscripcion_curso` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_inscripcion_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `jacquin_academia_db`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_estudiante`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `jacquin_academia_db`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
